application: biomaptini
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /styles
  static_dir: styles
- url: /scripts
  static_dir: scripts
- url: /event/.*
  script: events.py
- url: /.*
  script: main.py

libraries:
- name: jinja2
  version: latest
